const TagTypes = {
    users: "Users",
    companies: "Companies",
    tests: "Tests",
    categories: "Categories",
    courses: "Courses",
    categoryDropDown: "CategoryDropDown",
    me: "Me",
    faqs: "Faqs",
    total: "Total",
    userGrowth: "UserGrowth",
    candidates: "Candidates",
    stats: "Stats",
    contacts: "Contacts",
    subscribers: "Subscribers",
    admins: "Admins",
    colors: "Colors",
    information: "Information",
    products: "Products",
    product: "Product",
    sizes: "Sizes",
    colorDropDown: "ColorDropDown",
    policy: "Policy",
    orders: "Orders",
    order: "Order",
    incomeGrowth: "incomeGrowth",
    subsbscribers: "Subscribers",
    privacy: "Privacy",
    terms: "Terms",
    about: "About",
    help: "Help"
}

export default TagTypes;